[package]
name = "rustyrust"
version = "0.1.1"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
aes = "0.9.0"
anyhow = "1.0.102"
base64 = "0.22.1"
cbc = "0.2.0"
nanoid = "0.5.0"
pumpkin-plugin-api = { version = "0.1.0", git = "https://github.com/Pumpkin-MC/Pumpkin", package = "pumpkin-plugin-api" }
rand = "0.10.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
serde_yaml = "0.9.34"
tracing = "0.1"
tungstenite = "0.29.0"
