on:
  push:
    tags:
      - "*"

name: Publish

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: "Build"
        run: cargo build --release
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          path: 'target/wasm32-wasip2/release/rustyrust.wasm'